### ISSUE TITLE
Make a version tag

### ISSUE THREAD

**Issue by Eseperio** [macklus/yii2-redsys-tpv#2]
Currently installation is only allowed within development environments. Due redsys api is mature, and this component only renders a few items should have a version tag, in order to allow install on stable projects.

**Comment by macklus** [comment]
Hi @Eseperio 
this plugin is old, and is going to be deprecated in favor of https://github.com/macklus/yii2-payments, who has more features than this.

As far as i can, i check, backup and delete this repo, and redirect to new one.

my apologies
